export const DELHI_NCR_PROPERTIES = [
  {
    _id: 'p1',
    title: '3BHK Apartment — Sector 62, Noida',
    type: 'residential',
    subtype: 'apartment',
    price: 8500000,
    location: { address: 'Sector 62', city: 'Noida', state: 'UP' },
    size: 1450,
    bedrooms: 3,
    bathrooms: 2,
    floor: 8,
    totalFloors: 14,
    amenities: ['Parking', 'Gym', 'Swimming Pool', 'Security', 'Power Backup'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80'],
    description: 'Modern 3BHK apartment with great city view. Ready to move.',
    listedBy: { name: 'Rajesh Kumar' },
  },
  {
    _id: 'p2',
    title: '2BHK Flat — Dwarka Sector 10, Delhi',
    type: 'residential',
    subtype: 'apartment',
    price: 7200000,
    location: { address: 'Dwarka Sector 10', city: 'Delhi', state: 'Delhi' },
    size: 1100,
    bedrooms: 2,
    bathrooms: 2,
    floor: 3,
    totalFloors: 6,
    amenities: ['Parking', 'Lift', 'Security'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80'],
    description: 'Spacious 2BHK in prime Dwarka location near metro.',
    listedBy: { name: 'Priya Singh' },
  },
  {
    _id: 'p3',
    title: '4BHK Builder Floor — Gurgaon Sector 57',
    type: 'residential',
    subtype: 'house',
    price: 15000000,
    location: { address: 'Sector 57', city: 'Gurgaon', state: 'Haryana' },
    size: 2200,
    bedrooms: 4,
    bathrooms: 4,
    floor: 1,
    totalFloors: 4,
    amenities: ['Parking', 'Garden', 'Modular Kitchen', 'Power Backup', 'CCTV'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80'],
    description: 'Luxurious builder floor with private terrace and garden.',
    listedBy: { name: 'Amit Sharma' },
  },
  {
    _id: 'p4',
    title: 'Commercial Shop — Connaught Place, Delhi',
    type: 'commercial',
    subtype: 'shop',
    price: 25000000,
    location: { address: 'Connaught Place', city: 'Delhi', state: 'Delhi' },
    size: 800,
    bedrooms: 0,
    bathrooms: 1,
    floor: 0,
    totalFloors: 3,
    amenities: ['24/7 Security', 'Power Backup', 'Air Conditioning'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80'],
    description: 'Prime commercial space in the heart of CP. High footfall area.',
    listedBy: { name: 'Neha Gupta' },
  },
  {
    _id: 'p5',
    title: '1BHK Studio — Greater Noida West',
    type: 'residential',
    subtype: 'apartment',
    price: 3200000,
    location: { address: 'Tech Zone 4', city: 'Greater Noida', state: 'UP' },
    size: 650,
    bedrooms: 1,
    bathrooms: 1,
    floor: 5,
    totalFloors: 20,
    amenities: ['Gym', 'Security', 'Power Backup', 'Intercom'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80'],
    description: 'Affordable studio apartment perfect for working professionals.',
    listedBy: { name: 'Rohit Verma' },
  },
  {
    _id: 'p6',
    title: 'Farmhouse — Chattarpur, South Delhi',
    type: 'residential',
    subtype: 'house',
    price: 45000000,
    location: { address: 'Chattarpur', city: 'Delhi', state: 'Delhi' },
    size: 5000,
    bedrooms: 5,
    bathrooms: 6,
    floor: 0,
    totalFloors: 2,
    amenities: ['Private Pool', 'Garden', 'Parking x4', 'Staff Quarters', 'Home Theatre'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80'],
    description: 'Stunning farmhouse with lush greenery and private pool.',
    listedBy: { name: 'Sunita Kapoor' },
  },
  {
    _id: 'p7',
    title: 'Office Space — Cyber City, Gurgaon',
    type: 'commercial',
    subtype: 'office',
    price: 35000000,
    location: { address: 'DLF Cyber City', city: 'Gurgaon', state: 'Haryana' },
    size: 3000,
    bedrooms: 0,
    bathrooms: 4,
    floor: 12,
    totalFloors: 25,
    amenities: ['24/7 Access', 'Cafeteria', 'Conference Rooms', 'Parking', 'High Speed Internet'],
    status: 'Available',
    images: ['https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=600&q=80'],
    description: 'Grade A office space in the most sought-after business district.',
    listedBy: { name: 'Vikram Malhotra' },
  },
  {
    _id: 'p8',
    title: '2BHK Flat — Indirapuram, Ghaziabad',
    type: 'residential',
    subtype: 'apartment',
    price: 5500000,
    location: { address: 'Ahinsa Khand 2', city: 'Ghaziabad', state: 'UP' },
    size: 1050,
    bedrooms: 2,
    bathrooms: 2,
    floor: 6,
    totalFloors: 12,
    amenities: ['Parking', 'Gym', 'Children Play Area', 'Security'],
    status: 'Sold',
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80'],
    description: 'Well-maintained flat in popular Indirapuram township.',
    listedBy: { name: 'Anita Joshi' },
  },
];
